theme: jekyll-theme-slate
title: Hi friend, welcome to my portfolio!
description: Here you can learn every interesting thing there is to know about me and my career, so yes, it won't take you long, but feel free to contact me if you want to know something else or if something piques your interes!
